application: zionsoft-bible
version: 1
runtime: go
api_version: go1

handlers:
- url: /view
  static_dir: static
  secure: always

- url: /admin/.*
  script: _go_app
  login: admin
  secure: always

- url: /.*
  script: _go_app
  secure: always
